@echo off
echo Starting Conance Backend Services...

echo 1. Starting Postgres and Redis...
docker-compose up -d

echo 2. Waiting for database to be ready (5 seconds)...
timeout /t 5 /nobreak

echo 3. Running Database Migrations...
go run github.com/pressly/goose/v3/cmd/goose@latest -dir db/migrations postgres "postgres://conance_user:conance_password@localhost:5432/conance_db?sslmode=disable" up

echo 4. Seeding Database...
go run scripts/seed.go

echo 5. Starting API Server (in a new window)...
start cmd /k "go run cmd\api\main.go"

echo 6. Starting Background Worker (in a new window)...
start cmd /k "go run cmd\worker\main.go"

echo Everything is up and running!
